// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
    //seed: "tsx prisma/seed.ts", // needed if need to create auto entry while running migration, but not needed if you want to run seed manually after migration
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
